[build-system]
requires = ["robotpy-build>=2020.6.0,<2021.0.0"]

[tool.robotpy-build]
base_package = "wpiutil"

[tool.robotpy-build.wrappers."wpiutil"]
name = "wpiutil"
sources = ["wpiutil/src/main.cpp"]
extra_includes = ["wpiutil/src/type_casters"]

generate = [
    { PortForwarder = "wpi/PortForwarder.h" }
]
generation_data = "gen"

[tool.robotpy-build.wrappers."wpiutil".maven_lib_download]
artifact_id = "wpiutil-cpp"
group_id = "edu.wpi.first.wpiutil"
repo_url = "https://frcmaven.wpi.edu/artifactory/release"
version = "2021.3.1"

libs = ["wpiutil"]

[tool.robotpy-build.wrappers."wpiutil".type_casters]
"wpi_array_type_caster.h" =    ["wpi::array"]
"wpi_arrayref_type_caster.h" =    ["wpi::ArrayRef"]
"wpi_smallset_type_caster.h" =    ["wpi::SmallSet"]
"wpi_smallvector_type_caster.h" = ["wpi::SmallVector"]
"wpi_smallvectorimpl_type_caster.h" = ["wpi::SmallVectorImpl"]
"wpi_stringref_type_caster.h" =   ["wpi::StringRef"]
"wpi_twine_type_caster.h" =       ["wpi::Twine"]

[tool.robotpy-build.metadata]
name = "robotpy-wpiutil"
description = "Binary wrapper for FRC WPIUtil library"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-wpiutil"
license = "BSD-3-Clause"
install_requires = []
